<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowLeft, Box, Layers3, Pause, Play, Square, XOctagon } from '@lucide/vue'
import type { RuntimeCommandStatus } from '@/api/runtimeControl'
import type { MissionDetail } from '@/types/mission'
import type { RuntimeNode } from '@/types/monitoring'
import type { UnityTrajectoryFrame } from '@/stores/trajectory'
import type { MissionTrajectorySessionState } from '@/stores/missionTrajectorySession'
import type { VehicleQuickCommand } from '@/components/control/VehicleQuickControl.vue'
import UnifiedVehicleControl from '@/components/control/UnifiedVehicleControl.vue'
import MissionTrajectoryMap from './MissionTrajectoryMap.vue'

const props=defineProps<{detail:MissionDetail;nodes:RuntimeNode[];trajectoryFrame:UnityTrajectoryFrame|null;sessionState:MissionTrajectorySessionState;sessionRevision:number;selectedDeviceCode:string;feedback:Record<string,RuntimeCommandStatus|undefined>;operationalStates:Record<string,string|undefined>;busy?:boolean}>()
const emit=defineEmits<{close:[];select:[code:string];vehicleCommand:[command:VehicleQuickCommand];missionAction:[action:'pause'|'resume'|'complete'|'cancel'];events:[];modeChange:[mode:'2d'|'3d']}>()
const mode=ref<'2d'|'3d'>('2d')
const layers=ref(['轨迹','航路点','包围圈','安全区','通信链路'])
const recentEvents=computed(()=>props.detail.events.slice(0,5))
function setMode(next:'2d'|'3d'){mode.value=next;emit('modeChange',next)}
function close(){emit('modeChange','2d');emit('close')}
</script>
<template>
  <section class="mission-execution-overlay">
    <header class="execution-header"><button :disabled="busy" @click="close"><ArrowLeft :size="18"/>返回任务中心</button><div><small>{{ detail.mission.code }} · RUN {{ detail.currentRun?.runNo || '--' }}</small><h2>{{ detail.mission.name }}</h2></div><div class="execution-stats"><span>{{ detail.mission.status }}</span><span>{{ detail.mission.stage }}</span><span>在线 {{ nodes.filter(n=>n.status==='ONLINE'&&['UAV','USV'].includes(n.type)).length }}/{{ detail.devices.filter(d=>['UAV','USV'].includes(d.type||'')).length }}</span></div><div class="execution-actions"><button v-if="detail.mission.status==='RUNNING'" :disabled="busy" @click="emit('missionAction','pause')"><Pause :size="17"/>暂停任务</button><button v-if="detail.mission.status==='PAUSED'" :disabled="busy" @click="emit('missionAction','resume')"><Play :size="17"/>继续任务</button><button :disabled="busy||!['RUNNING','PAUSED'].includes(detail.mission.status)" @click="emit('missionAction','complete')"><Square :size="17"/>完成任务</button><button class="danger" :disabled="busy||!['RUNNING','PAUSED','READY'].includes(detail.mission.status)" @click="emit('missionAction','cancel')"><XOctagon :size="17"/>终止任务</button></div></header>
    <div class="execution-body">
      <aside class="execution-tree"><h3>作战对象</h3><section v-for="type in ['UAV','USV']" :key="type"><b>{{ type }}</b><button v-for="node in nodes.filter(n=>n.type===type)" :key="node.code" @click="emit('select',node.code)">{{ node.code.toUpperCase() }} <i :class="{online:node.status==='ONLINE'}"></i></button></section><section><b>图层</b><el-checkbox-group v-model="layers"><el-checkbox v-for="layer in ['轨迹','航路点','包围圈','安全区','通信链路']" :key="layer" :value="layer">{{ layer }}</el-checkbox></el-checkbox-group></section></aside>
      <main class="execution-stage"><div class="mode-switch"><button :class="{active:mode==='2d'}" @click="setMode('2d')"><Layers3 :size="16"/>2D 轨迹</button><button :class="{active:mode==='3d'}" @click="setMode('3d')"><Box :size="16"/>3D Unity</button></div><span class="shared-run-indicator">同一 RUN 实时数据</span><MissionTrajectoryMap v-if="mode==='2d'" :mission-name="detail.mission.name" :mission-status="detail.mission.status" :selected-device-code="selectedDeviceCode" :trajectory-frame="trajectoryFrame" :session-state="sessionState" :session-revision="sessionRevision" @select-device="emit('select',$event)"/><div v-else class="execution-unity-viewport" data-unity-runtime-viewport="mission-execution"></div></main>
      <aside class="execution-control"><UnifiedVehicleControl :devices="nodes" :selected-device-code="selectedDeviceCode" :feedback="feedback" :operational-states="operationalStates" :busy="busy" @select="emit('select',$event)" @command="emit('vehicleCommand',$event)"/><button class="all-events" @click="emit('events')">查看全部事件</button></aside>
    </div>
    <footer class="execution-footer"><article v-for="event in recentEvents" :key="event.id"><time>{{ new Date(event.occurredAt).toLocaleTimeString() }}</time><b>{{ event.title }}</b><span>{{ event.message }}</span></article></footer>
  </section>
</template>
<style scoped>
.mission-execution-overlay{position:fixed;inset:0;z-index:90;background:#020e15;color:#dff5f3;display:grid;grid-template-rows:auto 1fr auto}.execution-header{min-height:72px;display:flex;align-items:center;gap:18px;padding:10px 18px;border-bottom:1px solid #17414b;background:linear-gradient(90deg,#041923,#03131c)}.execution-header button,.mode-switch button{display:flex;align-items:center;gap:6px;border:1px solid #2a515b;background:#08232d;color:#cde2e2;border-radius:5px;padding:8px 11px;cursor:pointer}.execution-header button:disabled{cursor:not-allowed;opacity:.45}.execution-header h2{margin:3px 0;font-size:18px}.execution-header small{color:#53d4e2}.execution-stats{margin-left:auto;display:flex;gap:7px;color:#8fb0b4}.execution-stats span{padding:5px 8px;background:rgba(62,151,168,.06);border:1px solid rgba(70,156,173,.14);border-radius:4px;font-size:10px}.execution-actions{display:flex;gap:7px}.execution-actions .danger{border-color:#8c3940;color:#ff7474}.execution-body{min-height:0;display:grid;grid-template-columns:190px minmax(0,1fr) 350px;gap:10px;padding:10px}.execution-tree,.execution-control{overflow:auto;border:1px solid #173d47;background:#041822;padding:12px}.execution-tree section{display:grid;gap:6px;margin:14px 0}.execution-tree section>b{color:#6ce4d5}.execution-tree button{display:flex;justify-content:space-between;border:0;background:#09212b;color:#b8d0d1;padding:8px}.execution-tree i{width:7px;height:7px;border-radius:50%;background:#64777a}.execution-tree i.online{background:#55e7a7}.execution-tree :deep(.el-checkbox-group){display:grid}.execution-stage{position:relative;min-height:0;border:1px solid #17414b;background:#03141c;overflow:hidden}.execution-stage :deep(.mission-trajectory-map){width:100%;height:100%}.mode-switch{position:absolute;z-index:3;top:10px;left:50%;transform:translateX(-50%);display:flex}.mode-switch .active{border-color:#6ce4d5;color:#6ce4d5;background:#0b3540}.shared-run-indicator{position:absolute;z-index:3;right:12px;top:14px;color:#59dcad;font-size:9px}.shared-run-indicator::before{display:inline-block;width:6px;height:6px;margin-right:5px;background:#55e7a7;border-radius:50%;box-shadow:0 0 7px #55e7a7;content:""}.execution-unity-viewport{width:100%;height:100%}.all-events{width:100%;margin-top:10px;height:36px;border:1px solid #2b5660;background:#08232d;color:#d7eeee}.execution-footer{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;padding:9px 12px;border-top:1px solid #173d47}.execution-footer article{min-width:0;padding:8px;background:#061b24}.execution-footer time,.execution-footer b,.execution-footer span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.execution-footer time{color:#5f8b91;font-size:10px}.execution-footer span{color:#89a8ac;font-size:11px}@media(max-width:1200px){.execution-body{grid-template-columns:160px minmax(0,1fr) 300px}.execution-header{flex-wrap:wrap}.execution-stats{margin-left:0}}
</style>
