import type {
    AlgorithmMissionPreview,
    AlgorithmMissionType,
  } from '@/types/algorithmMission'
  
  const capturePreview: AlgorithmMissionPreview = {
    summary: {
      missionType: 'CAPTURE',
      algorithmName: 'GBSFLA协同围捕',
      status: 'ENCIRCLING',
      statusName: '形成包围',
      targetId: 'target_01',
      participatingUavs: 3,
      participatingUsvs: 2,
      progress: 72,
      elapsedSeconds: 86,
      degraded: false,
      detail: '异构平台正在向目标周围的围捕位置收敛。',
    },
    scene: {
      centerLabel: '围捕目标 target_01',
      centerX: 125.6,
      centerY: 78.3,
      threatLabel: null,
      threatX: null,
      threatY: null,
    },
    assignments: [
      {
        vehicleId: 'uav_01',
        vehicleType: 'UAV',
        roleName: '空中观察',
        targetId: 'target_01',
        targetX: 118.5,
        targetY: 84.2,
        assignmentCost: 0.21,
        active: true,
        status: '接近围捕位置',
      },
      {
        vehicleId: 'uav_02',
        vehicleType: 'UAV',
        roleName: '空中观察',
        targetId: 'target_01',
        targetX: 132.4,
        targetY: 82.7,
        assignmentCost: 0.26,
        active: true,
        status: '保持目标跟踪',
      },
      {
        vehicleId: 'uav_03',
        vehicleType: 'UAV',
        roleName: '空中观察',
        targetId: 'target_01',
        targetX: 126.8,
        targetY: 68.9,
        assignmentCost: 0.24,
        active: true,
        status: '调整包围角度',
      },
      {
        vehicleId: 'usv_01',
        vehicleType: 'USV',
        roleName: '水面拦截',
        targetId: 'target_01',
        targetX: 112.3,
        targetY: 75.6,
        assignmentCost: 0.34,
        active: true,
        status: '向拦截点航行',
      },
      {
        vehicleId: 'usv_02',
        vehicleType: 'USV',
        roleName: '水面拦截',
        targetId: 'target_01',
        targetX: 139.7,
        targetY: 76.1,
        assignmentCost: 0.37,
        active: true,
        status: '向拦截点航行',
      },
    ],
    events: [
      {
        id: 'capture-03',
        time: '10:31:26',
        level: 'INFO',
        stage: '形成包围',
        message: '围捕半径正在收缩，5个平台保持有效分配。',
      },
      {
        id: 'capture-02',
        time: '10:30:58',
        level: 'INFO',
        stage: '接近目标',
        message: 'USV-01和USV-02已获得水面拦截位置。',
      },
      {
        id: 'capture-01',
        time: '10:30:12',
        level: 'SUCCESS',
        stage: '目标跟踪',
        message: '已锁定目标target_01并完成首轮角色分配。',
      },
    ],
  }
  
  const escortPreview: AlgorithmMissionPreview = {
    summary: {
      missionType: 'ESCORT_DEFENSE',
      algorithmName: '异构集群护航防守',
      status: 'INTERCEPTING',
      statusName: '拦截威胁',
      targetId: 'escort_target_01',
      participatingUavs: 3,
      participatingUsvs: 3,
      progress: 64,
      elapsedSeconds: 103,
      degraded: false,
      detail: '前方守卫正在拦截敌方目标，其余平台维持护航阵型。',
    },
    scene: {
      centerLabel: '被护航目标 escort_target_01',
      centerX: 110,
      centerY: 85,
      threatLabel: '威胁目标 enemy_01',
      threatX: 158.2,
      threatY: 105.6,
    },
    assignments: [
      {
        vehicleId: 'uav_01',
        vehicleType: 'UAV',
        roleName: '威胁侦察',
        targetId: 'enemy_01',
        targetX: 158.2,
        targetY: 105.6,
        assignmentCost: 0.18,
        active: true,
        status: '持续跟踪威胁',
      },
      {
        vehicleId: 'uav_02',
        vehicleType: 'UAV',
        roleName: '左翼护航',
        targetId: 'escort_target_01',
        targetX: 103.5,
        targetY: 91.2,
        assignmentCost: 0.23,
        active: true,
        status: '保持护航位置',
      },
      {
        vehicleId: 'uav_03',
        vehicleType: 'UAV',
        roleName: '右翼护航',
        targetId: 'escort_target_01',
        targetX: 116.8,
        targetY: 90.7,
        assignmentCost: 0.22,
        active: true,
        status: '保持护航位置',
      },
      {
        vehicleId: 'usv_01',
        vehicleType: 'USV',
        roleName: '前方拦截',
        targetId: 'enemy_01',
        targetX: 136.4,
        targetY: 101.8,
        assignmentCost: 0.28,
        active: true,
        status: '进入拦截位置',
      },
      {
        vehicleId: 'usv_02',
        vehicleType: 'USV',
        roleName: '左侧守卫',
        targetId: 'escort_target_01',
        targetX: 101.2,
        targetY: 83.4,
        assignmentCost: 0.31,
        active: true,
        status: '维持防守弧线',
      },
      {
        vehicleId: 'usv_03',
        vehicleType: 'USV',
        roleName: '右侧守卫',
        targetId: 'escort_target_01',
        targetX: 119.1,
        targetY: 83.8,
        assignmentCost: 0.32,
        active: true,
        status: '维持防守弧线',
      },
    ],
    events: [
      {
        id: 'escort-03',
        time: '10:34:25',
        level: 'WARNING',
        stage: '拦截威胁',
        message: '敌方目标进入防守触发范围，USV-01执行前方拦截。',
      },
      {
        id: 'escort-02',
        time: '10:33:47',
        level: 'INFO',
        stage: '防守重组',
        message: '异构平台已完成威胁方向重组。',
      },
      {
        id: 'escort-01',
        time: '10:32:42',
        level: 'SUCCESS',
        stage: '正常护航',
        message: '护航阵型建立完成，目标状态正常。',
      },
    ],
  }
  
  export function getAlgorithmMissionPreview(
    missionType: AlgorithmMissionType,
  ): AlgorithmMissionPreview {
    return missionType === 'CAPTURE' ? capturePreview : escortPreview
  }