/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConsoleLayout: typeof import('./components/layout/ConsoleLayout.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MissionConfigDialog: typeof import('./components/mission/MissionConfigDialog.vue')['default']
    MissionEventDrawer: typeof import('./components/mission/MissionEventDrawer.vue')['default']
    MissionExecutionOverlay: typeof import('./components/mission/MissionExecutionOverlay.vue')['default']
    MissionGroupControl: typeof import('./components/control/MissionGroupControl.vue')['default']
    MissionListPanel: typeof import('./components/mission/MissionListPanel.vue')['default']
    MissionStartCheckDialog: typeof import('./components/mission/MissionStartCheckDialog.vue')['default']
    MissionTrajectoryMap: typeof import('./components/mission/MissionTrajectoryMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnifiedVehicleControl: typeof import('./components/control/UnifiedVehicleControl.vue')['default']
    UnityRuntimeHost: typeof import('./components/unity/UnityRuntimeHost.vue')['default']
    UnityWebglPanel: typeof import('./components/unity/UnityWebglPanel.vue')['default']
    VehicleGlyph: typeof import('./components/control/VehicleGlyph.vue')['default']
    VehicleQuickControl: typeof import('./components/control/VehicleQuickControl.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
